// Identities verified against the linked first-party pages on 2026-09-29.
// Cities are representative practice locations, not claims about headquarters.
// Focus, difficulty, timers and dialogue are authored game scenarios.
export const regions = [
  ["all", "Мир", "World"],
  ["cis", "СНГ", "CIS"],
  ["us", "Америка", "Americas"],
  ["eu", "Европа", "Europe"],
  ["uae", "Ближний Восток", "Middle East"],
  ["asia", "Азия", "Asia"],
  ["africa", "Африка", "Africa"],
  ["oceania", "Океания", "Oceania"],
];
const fund = (
  id,
  title,
  region,
  country,
  city,
  coordinates,
  symbol,
  level,
  source,
  focus,
  people,
) => ({
  id,
  title: [title, title],
  region,
  country,
  city,
  coordinates,
  symbol,
  level,
  source,
  focus,
  people,
});
// name, English name, stable id. Organization affiliation is given without job-title claims.
const funds = [
  fund(
    "sequoia",
    "Sequoia Capital",
    "us",
    "840",
    ["Менло-Парк, США", "Menlo Park, USA"],
    [-122.18, 37.45],
    "SC",
    5,
    "https://sequoiacap.com/our-team",
    ["Клиент и масштаб рынка", "Customer and market scale"],
    [
      ["Альфред Лин", "Alfred Lin", "alfred"],
      ["Джим Гетц", "Jim Goetz", "jim-goetz"],
    ],
  ),
  fund(
    "accel",
    "Accel",
    "us",
    "840",
    ["Пало-Альто, США", "Palo Alto, USA"],
    [-122.14, 37.44],
    "AC",
    4,
    "https://www.accel.com/team",
    ["Повторяемые продажи", "Repeatable sales"],
    [
      ["Эндрю Брачча", "Andrew Braccia", "braccia"],
      ["Рич Вонг", "Rich Wong", "rich-wong"],
    ],
  ),
  fund(
    "bessemer",
    "Bessemer Venture Partners",
    "us",
    "840",
    ["Сан-Франциско, США", "San Francisco, USA"],
    [-122.42, 37.77],
    "BV",
    4,
    "https://www.bvp.com/team",
    ["Удержание и экономика SaaS", "SaaS retention and economics"],
    [
      ["Байрон Дитер", "Byron Deeter", "deeter"],
      ["Талия Голдберг", "Talia Goldberg", "talia"],
    ],
  ),
  fund(
    "founders-fund",
    "Founders Fund",
    "us",
    "840",
    ["Сан-Франциско, США", "San Francisco, USA"],
    [-122.42, 37.77],
    "FF",
    5,
    "https://foundersfund.com/our_team/",
    ["Уникальность решения", "Distinctive solution"],
    [["Питер Тиль", "Peter Thiel", "thiel"]],
  ),
  fund(
    "500global",
    "500 Global",
    "us",
    "840",
    ["Сан-Франциско, США", "San Francisco, USA"],
    [-122.42, 37.77],
    "500",
    3,
    "https://500.co/team",
    ["Проверка спроса и рост", "Demand validation and growth"],
    [["Кристин Цай", "Christine Tsai", "tsai"]],
  ),
  fund(
    "index",
    "Index Ventures",
    "eu",
    "826",
    ["Лондон, Великобритания", "London, UK"],
    [-0.13, 51.5],
    "IX",
    4,
    "https://www.indexventures.com/team/jan-hammer/",
    ["Данные и финансовый продукт", "Data and financial products"],
    [["Ян Хаммер", "Jan Hammer", "jan-hammer"]],
  ),
  fund(
    "balderton",
    "Balderton Capital",
    "eu",
    "826",
    ["Лондон, Великобритания", "London, UK"],
    [-0.13, 51.5],
    "BC",
    4,
    "https://www.balderton.com/team/",
    ["Выход на международный рынок", "International expansion"],
    [
      ["Суранга Чандратиллаке", "Suranga Chandratillake", "suranga"],
      ["Бернард Лиото", "Bernard Liautaud", "bernard"],
    ],
  ),
  fund(
    "seedcamp",
    "Seedcamp",
    "eu",
    "826",
    ["Лондон, Великобритания", "London, UK"],
    [-0.13, 51.5],
    "SE",
    3,
    "https://seedcamp.com/our-team/",
    ["Первый клиент и команда", "First customer and team"],
    [
      ["Решма Сохони", "Reshma Sohoni", "reshma"],
      ["Карлос Эспиналь", "Carlos Eduardo Espinal", "carlos"],
    ],
  ),
  fund(
    "point-nine",
    "Point Nine",
    "eu",
    "276",
    ["Берлин, Германия", "Berlin, Germany"],
    [13.4, 52.52],
    "P9",
    4,
    "https://www.pointnine.com/?lang=en",
    ["SaaS и повторяемая выручка", "SaaS and recurring revenue"],
    [
      ["Кристоф Янц", "Christoph Janz", "janz"],
      ["Павел Худзинский", "Pawel Chudzinski", "pawel"],
    ],
  ),
  fund(
    "partech",
    "Partech",
    "eu",
    "250",
    ["Париж, Франция", "Paris, France"],
    [2.35, 48.86],
    "PT",
    4,
    "https://partechpartners.com/",
    ["Масштабирование продукта", "Product scaling"],
    [["Филипп Колломбель", "Philippe Collombel", "collombel"]],
  ),
  fund(
    "iidf",
    "ФРИИ / IIDF",
    "cis",
    "643",
    ["Москва, Россия", "Moscow, Russia"],
    [37.62, 55.75],
    "И",
    3,
    "https://iidf.ru/fond/team/",
    ["Продажи и подтверждение спроса", "Sales and demand evidence"],
    [
      ["Кирилл Варламов", "Kirill Varlamov", "varlamov"],
      ["Дмитрий Калаев", "Dmitry Kalaev", "kalaev"],
    ],
  ),
  fund(
    "voskhod",
    "Восход / Voskhod",
    "cis",
    "643",
    ["Москва, Россия", "Moscow, Russia"],
    [37.62, 55.75],
    "В",
    4,
    "https://voskhod.digital/",
    ["Технология и путь к рынку", "Technology and route to market"],
    [["Руслан Саркисов", "Ruslan Sarkisov", "sarkisov"]],
  ),
  fund(
    "most",
    "MOST Ventures",
    "cis",
    "398",
    ["Алматы, Казахстан", "Almaty, Kazakhstan"],
    [76.89, 43.24],
    "MV",
    3,
    "https://mostecosystem.com/team",
    ["Первые продажи за пределами рынка", "First sales beyond the home market"],
    [
      ["Алим Хамитов", "Alim Khamitov", "alim"],
      ["Павел Коктышев", "Pavel Koktyshev", "pavel"],
    ],
  ),
  fund(
    "ma7",
    "MA7 Ventures",
    "cis",
    "398",
    ["Алматы, Казахстан", "Almaty, Kazakhstan"],
    [76.89, 43.24],
    "M7",
    4,
    "https://ma7.vc/",
    ["MVP и рыночная проверка", "MVP and market validation"],
    [["Мурат Абдрахманов", "Murat Abdrakhmanov", "murat"]],
  ),
  fund(
    "beco",
    "BECO Capital",
    "uae",
    "784",
    ["Дубай, ОАЭ", "Dubai, UAE"],
    [55.27, 25.2],
    "BE",
    4,
    "https://www.becocapital.com/",
    ["Выход на рынок MENA", "MENA market entry"],
    [],
  ),
  fund(
    "mevp",
    "MEVP",
    "uae",
    "784",
    ["Дубай, ОАЭ", "Dubai, UAE"],
    [55.27, 25.2],
    "ME",
    4,
    "https://www.mevp.com/team/walidmansour",
    ["Локализация и экономика роста", "Localization and growth economics"],
    [["Валид Мансур", "Walid Mansour", "walid"]],
  ),
  fund(
    "peak-xv",
    "Peak XV Partners",
    "asia",
    "356",
    ["Бенгалуру, Индия", "Bengaluru, India"],
    [77.59, 12.97],
    "XV",
    4,
    "https://www.peakxv.com/our-team",
    ["Продукт для большого рынка", "Product for a large market"],
    [
      ["Шайлендра Сингх", "Shailendra Singh", "shailendra"],
      ["Раджан Анандан", "Rajan Anandan", "rajan"],
    ],
  ),
  fund(
    "antler",
    "Antler",
    "asia",
    "702",
    ["Сингапур", "Singapore"],
    [103.82, 1.35],
    "AN",
    3,
    "https://www.antler.co/spokesperson/magnus-grimeland",
    ["Команда и проверка гипотезы", "Team and hypothesis validation"],
    [["Магнус Гримеланд", "Magnus Grimeland", "magnus"]],
  ),
  fund(
    "kaszek",
    "Kaszek",
    "us",
    "076",
    ["Сан-Паулу, Бразилия", "São Paulo, Brazil"],
    [-46.63, -23.55],
    "KZ",
    4,
    "https://www.kaszek.com/people/",
    ["Экспансия в Латинской Америке", "Latin American expansion"],
    [
      ["Эрнан Касах", "Hernan Kazah", "hernan"],
      ["Николас Секаси", "Nicolas Szekasy", "szekasy"],
    ],
  ),
  fund(
    "partech-africa",
    "Partech Africa",
    "africa",
    "686",
    ["Дакар, Сенегал", "Dakar, Senegal"],
    [-17.45, 14.69],
    "PA",
    4,
    "https://partechpartners.com/",
    ["Дистрибуция и доступность продукта", "Distribution and product access"],
    [["Тиджан Деме", "Tidjane Dème", "tidjane"]],
  ),
  fund(
    "blackbird",
    "Blackbird",
    "oceania",
    "036",
    ["Сидней, Австралия", "Sydney, Australia"],
    [151.21, -33.87],
    "BB",
    4,
    "https://www.blackbird.vc/team/niki-scevak",
    ["Глобальный продукт с первого дня", "Global product from day one"],
    [["Ники Шевак", "Niki Scevak", "niki"]],
  ),
];
const portraits = {
  alfred: "/portraits/alfred.webp",
  "jim-goetz": "/portraits/jim-goetz.webp",
  murat: "/portraits/murat.jpg",
  suranga: "/portraits/suranga.jpg",
  bernard: "/portraits/bernard.jpg",
  braccia: "/portraits/braccia.jpg",
  "rich-wong": "/portraits/rich-wong.jpg",
  deeter: "/portraits/deeter.png",
  talia: "/portraits/talia.png",
  tsai: "/portraits/tsai.png",
  "jan-hammer": "/portraits/jan-hammer.png",
  janz: "/portraits/janz.jpg",
  pawel: "/portraits/pawel.jpg",
  shailendra: "/portraits/shailendra.webp",
  rajan: "/portraits/rajan.webp",
  magnus: "/portraits/magnus.avif",
  niki: "/portraits/niki.avif",
  collombel: "/portraits/collombel.webp",
  tidjane: "/portraits/tidjane.webp",
  varlamov: "/portraits/varlamov.png",
  kalaev: "/portraits/kalaev.png",
  alim: "/portraits/alim.png",
  pavel: "/portraits/pavel.png",
  walid: "/portraits/walid.jpg",
  hernan: "/portraits/hernan.jpg",
  szekasy: "/portraits/szekasy.jpg",
  marc: "/portraits/marc.png",
  ben: "/portraits/ben.png",
  thiel: "/portraits/thiel.jpg",
  sarkisov: "/portraits/sarkisov.png",
  reshma: "/portraits/reshma.jpg",
  carlos: "/portraits/carlos.jpg",
};
export const worldInvestors = funds
  .flatMap((f) =>
    f.people.map(([ru, en, id]) => ({
      id,
      name: [ru, en],
      role: id === "pavel" ? "MOST Holding" : f.title[1],
      initial: en
        .split(" ")
        .map((w) => w[0])
        .slice(0, 2)
        .join(""),
      color: "blue",
      photo: portraits[id] || null,
      ...(id === "janz" ? { photoPosition: "85% 25%" } : {}),
      level: f.level,
      region: f.region,
      country: f.country,
      arenaId: f.id,
      source: f.source,
      focus: f.focus,
      verifiedAt: "2026-09-29",
    })),
  )
  .concat(
    [
      {
        id: "marc",
        name: ["Марк Андриссен", "Marc Andreessen"],
        initial: "MA",
        role: "a16z",
        arenaId: "a16z",
      },
      {
        id: "ben",
        name: ["Бен Хоровиц", "Ben Horowitz"],
        initial: "BH",
        role: "a16z",
        arenaId: "a16z",
      },
    ].map((p) => ({
      ...p,
      photo: portraits[p.id] || null,
      color: "blue",
      level: 5,
      region: "us",
      country: "840",
      source: "https://a16z.com/team/",
      focus: ["Технология и венчурный масштаб", "Technology and venture scale"],
      verifiedAt: "2026-09-29",
    })),
  );
export const worldArenas = funds.map((f) => ({
  ...Object.fromEntries(
    Object.entries(f).filter(([k]) => !["people", "focus"].includes(k)),
  ),
  title: f.id === "iidf" ? ["ФРИИ", "IIDF"] : f.title,
  kind: "venture",
  tag: ["МЕЖДУНАРОДНЫЙ КАТАЛОГ", "GLOBAL DIRECTORY"],
  subtitle: f.focus,
  description: [
    `Учебная симуляция по мотивам ${f.title[0]}. Фокус сценария: ${f.focus[0].toLowerCase()}. Это не встреча с фондом; вопросы и лимиты придуманы для тренировки.`,
    `A practice simulation inspired by ${f.title[1]}. Scenario focus: ${f.focus[1].toLowerCase()}. This is not a meeting with the firm; questions and limits are game settings.`,
  ],
  difficulty: f.level >= 4 ? ["Эксперт", "Expert"] : ["Сложный", "Advanced"],
  pitchSeconds: 120,
  time: 8,
  xp: f.level * 70,
  mapPosition: [500, 230],
  ...(f.people.length ? { personaIds: f.people.map((p) => p[2]) } : {}),
  verifiedAt: "2026-09-29",
}));
